name: Daily File Creator

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

permissions:
  contents: write

# Isse Node.js 24 force hoga aur warning khatam ho jayegi
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Daily File
        run: |
          # Indian Timezone ke hisaab se date set karne ke liye
          TODAY=$(TZ="Asia/Kolkata" date +'%d-%m-%Y')
          FILENAME="file_${TODAY}.txt"
          echo "Today date is ${TODAY}" > $FILENAME
          echo "File created: $FILENAME"

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add daily file for $(TZ="Asia/Kolkata" date +'%d-%m-%Y')" || exit 0
          git push